sudo: required
services:
  - docker
language: python
python:
  - "3.6"
install:
  - pip3 install git+https://github.com/nextstrain/cli
  - nextstrain version
  - nextstrain check-setup
  - nextstrain update
script:
  - mkdir -p data/
  - cp -v example_data/h3n2_ha.fasta data/
  - cp -v example_data/h3n2_na.fasta data/
  - cp -v example_data/h3n2_hi_titers.tsv data/h3n2_public_hi_cell_titers.tsv
  - cp -v example_data/h3n2_hi_titers.tsv data/h3n2_cdc_hi_cell_titers.tsv
  - nextstrain build . auspice/flu_seasonal_h3n2_ha_12y_tree.json auspice/flu_seasonal_h3n2_ha_12y_tip-frequencies.json
